#!/usr/bin/env sh

echo "🔍 Validating commit message..."

pnpm exec commitlint --edit "$1"

if [ $? -eq 0 ]; then
  echo "✅ Commit message is valid."
else
  echo "❌ Commit message is invalid. Please follow the commit message conventions."
  exit 1
fi