#!/usr/bin/env sh

echo "🧹 Running pre-commit checks..."

echo "Current working directory: $(pwd)"

pnpm run type-check
pnpm run lint 
pnpm run format

if [ $? -eq 0 ]; then
  echo "✅ Pre-commit checks passed successfully!"
else
  echo "❌ Pre-commit checks failed. Please fix the issues and try again."
  exit 1
fi
