#!/usr/bin/env sh

echo "🚀 Running pre-push checks..."

pnpm run lint 
pnpm run format

if [ $? -eq 0 ]; then
  echo "✅ Lint and format passed. Proceeding with push."
else
  echo "❌ Pre-push checks failed. Please fix the issues before pushing."
  exit 1
fi
