name: Continuous Integration | Lint, Format & Commit Check

on:
  push:
    branches:
      - dev
      - task/*
  pull_request:
    branches:
      - dev
      - qa
      - staging
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run linters
        run: pnpm run lint

      - name: Check formatting
        run: pnpm run format:check

      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v3
        with:
          configFile: commitlint.config.cjs
